const words = [
    "apple", "backpack", "camera", "diamond", "elephant", "fire truck", "guitar", "helicopter",
    "igloo", "jellyfish", "kangaroo", "lighthouse", "moon", "ninja", "octopus", "penguin",
    "queen", "rainbow", "snowman", "tornado", "unicorn", "vampire", "watermelon", "xylophone",
    "yacht", "zebra", "astronaut", "butterfly", "castle", "dragon", "eyeball", "french fries",
    "ghost", "hamburger", "island", "jungle", "keyboard", "lemon", "mountain", "notebook",
    "ocean", "pizza", "quill", "robot", "spider", "telescope", "umbrella", "volcano",
    "wizard", "alien", "basketball", "cactus", "dolphin", "earth", "fence", "glasses" , "balloon" , 
    "candle" , "eagle", "donut", "ferris wheel", "gorilla", "hammer", "iguana", "lizard", "salamander",
    "jacket", "koala", "mailbox", "necklace", "ostrich", "pancake", "rocket", "shovel", "Yoyo", "zipper",
    "airplane", "banana", "carrot", "drum", "envelope", "feather", "grapes", "house", "ice cream", "jelly jar",
    "kite", "lamp", "magnet", "nest", "orange", "parrot", "ring", "sandwich", "television", "unicorn horn",
    "vase", "wheel", "axe", "yarn", "zoo", "ant", "bear", "cloud", "desk", "ear", "frog", "garden",
    "hat", "igloo door", "jeep", "key", "leaf", "mushroom", "nail", "owl", "pen", "quilt", "rope", 
    "sock", "tiger", "van", "window", "xylophone mallet", "yogurt", "zipper bag", "apple pie", "bed", 
    "chair", "dice", "egg", "fish", "gift", "heart", "ice cube", "juice", "knife", "lion", "mirror", 
    "net", "pear", "queen crown", "road", "star", "turtle", "volcano lava", "watch", "axe handle", 
    "yard", "zebra stripes", "astronaut helmet","SpongeBob", "Patrick Star", "Squidward", "Mr Krabs", "Plankton",
    "Homer Simpson","Bugs Bunny", "Daffy Duck", "Tweety", "Sylvester", "Elmer Fudd", "Tom", "Jerry", "Scooby-Doo", 
    "Shaggy", "Velma", "Fred Jones", "Shinchan", "Gian", "Nobita", "Doraemon", "Batman", "Superman", "Spider-Man", 
    "Iron Man", "Hulk", "Captain America", "Thor", "Black Panther", "Donald Duck", "Goofy", "Mickey Mouse"
    , "Pluto","Donald Trump", "Narendra Modi", "Imran Khan", "Bilawal Bhutto","Shah Rukh Khan", 
    "Salman Khan", "Virat Kohli", "MS Dhoni", "Kim Jong Un", "Elon Musk", "Bill Gates", "Mark Zuckerberg",
    "Suneo Honekawa", "Mr Bean", "Santa Claus", "Dee Dee", "Shrek",  "Olaf", "Elsa", "Anna", 
    "Parallel universe", "CAPTCHA", "Notification", "awkward silence", "regret", "break up", "jealousy",
    "deja vu", "trauma", "traffic signal", "mosquito racket", "stapler", "hippopotamus monster", "bacteria",
    "amoeba", "mitochondria", "Angry Potato", "bouquet", "art supplies", "singer", "anime", "dragon",
    "mermaid", "centaur", "griffin", "werewolf", "vampire", "goth", "christmas tree", "mannequin",
    "galaxy", "masquerade", "typography", "soldier", "friendship", "soul", "party", "dreams", "minions",
    "demons", "pinecone", "CD case", "tattoo", "broken egg shells", "gothic dress", "teardrop", "sword",
    "dagger", "dragongly", "frog", "night sky", "gentleman","diva", "shipwreck", "night walk", "guardian",
    "mushroom", "medusa", "bow and arrow", "ballerina", "ice skating", "sneezing", "garbage", "selfie",
    "ambulance", "submarine", "sandcstle", "hot air balloon", "keyhole", "manhole", "cookbook", "catfish",
    "Paris", "Beach", "Mountains", "Hawaii", "Mount Rushmore", "USA", "Hospital", "Attic", "Japan", 
    "Library", "Desert", "Mars", "Washington DC", "Las Vegas", "Train station", "North Pole", "Farm", 
    "Disney World", "Mexico", "drought", "professor", "barber", "kneel", "orbit", "germ", "darts", 
    "dance", "cape", "beanstalk", "sushi", "baby-sitter", "ping pong", "mime", "Heinz 57", "half", 
    "swamp", "sheep dog", "macaroni", "hurdle", "Internet", "lie", "logo", "rind", "fireman pole", 
    "raft", "wig", "salmon", "pigpen", "letter opener", "cabin", "fireside", "cell phone charger", 
    "dent", "jungle", "dripping", "saddle", "fabric", "sleep", "mirror", "ski goggles", "ringleader", 
    "scream", "point", "neighborhood", "yardstick", "applause", "cliff", "loveseat", "sponge", "chess", 
    "grandpa", "peasant", "cruise", "CD", "drawback", "chestnut", "yolk", "pilot", "season", "bedbug", 
    "world", "important", "bleach", "biscuit", "bobsled", "pharmacist", "shampoo", "swarm", "moth", 
    "sneeze", "deep", "sunburn", "pizza sauce", "houseboat", "password", "dryer sheets", "migrate", 
    "snag", "koala", "catalog", "husband", "darkness", "shower curtain", "rib", "extension cord", 
    "honk", "landscape", "water buffalo", "wooly mammoth", "cheerleader", "cloak", "birthday", 
    "nightmare", "fizz", "clog", "myth", "wind", "banister", "post office", "knight", "rim", "think", 
    "bride", "comfy", "hydrogen", "baguette", "vitamin", "lace", "tiptoe", "sweater vest", "pail", 
    "glitter", "plow", "retail", "leak", "pocket", "crust", "mascot", "macho", "hail", "bargain", 
    "time machine", "drain", "vegetarian", "bookend", "ivy", "taxi", "foil", "mast", "gold", "chime", 
    "commercial", "quicksand", "crow's nest", "lap", "diagonal", "juggle", "dorsal", "exercise", "drip", 
    "boa constrictor", "handle", "rubber", "speakers", "s'mores", "fiddle", "puppet", "pro", "jazz", 
    "cardboard", "dream", "glue stick", "bonnet", "chef", "runt", "plank", "full", "ditch", "hut", 
    "whisk", "avocado", "zipper", "dizzy", "oar", "mold", "recycle", "wag", "fog", "bald", "ceiling fan", 
    "traffic jam", "firefighter", "picnic", "newsletter", "wax", "shrew", "dentist", "gasoline", "brand", 
    "welder", "wedding cake", "dashboard", "caviar", "laser", "download", "baggage", "bruise", "punk", 
    "sandbox", "hot tub", "shrink ray", "safe", "goblin", "baseboards", "dust bunny", "double", "wobble", 
    "coach", "lung", "zoo", "pen", "caterpillar", "rocket", "alligator", "pizza", "shirt", "kite", 
    "eyes", "chair", "cup", "jacket", "hippo", "bird", "monster", "bracelet", "coat", "balloon", 
    "dinosaur", "head", "book", "mouse", "smile", "bridge", "blocks", "milk", "eye", "oval", 
    "snowflake", "broom", "cheese", "lion", "lips", "beach", "cloud", "bus", "elephant", "sunglasses", 
    "lemon", "star", "spoon", "boat", "turtle", "drum", "doll", "ant", "motorcycle", "bike", "pencil", 
    "bunk bed", "moon", "inchworm", "slide", "hat", "cat", "tail", "helicopter", "square", "Mickey Mouse",
    "octopus", "door", "table", "egg", "bell", "nose", "spider", "horse", "finger", "glasses", "jar", 
    "girl", "ear", "lizard", "flower", "snowman", "baby", "car", "bread", "blanket", "apple", "bench", 
    "skateboard", "pig", "ice cream cone", "frog", "feet", "lollipop", "heart", "ears", "bed", "carrot", 
    "person", "boy", "train", "truck", "bug", "legs", "bowl", "lamp", "desk", "purse", "light", 
    "mountain", "snail", "basketball", "orange", "bear", "chicken", "grass", "cookie", "clock", "ghost", 
    "spider web", "ocean", "monkey", "shoe", "dog", "face", "circle", "water", "butterfly", "house", 
    "robot", "mouth", "branch", "worm", "socks", "grapes", "crab", "banana", "computer", "bee", "whale", 
    "seashell", "snake", "sun", "swing", "bat", "pie", "wheel", "bunny", "hand", "cherry", "jellyfish", 
    "tree", "stairs", "duck", "leaf", "dragon", "giraffe", "ball", "pants", "ring", "airplane", "candle", 
    "cow", "cupcake", "football", "hamburger", "bone", "corn", 
    "Rose The Great", "my game my rules"
]; 

// This makes the array available for server.js to use
module.exports = words;